groups:
  - name: default
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute(s)."
    - alert: HostOutOfMemory
      expr: (100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)) > 70
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Host out of memory (instance {{ $labels.instance }})"
        description: "Node memory is filling up (< 30% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: HostHighCpuLoad
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Host high CPU load (instance {{ $labels.instance }})"
        description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: WindowsServerCpuUsage
      expr: 100 - (avg by (instance) (rate(wmi_cpu_time_total{mode="idle"}[2m])) * 100) > 80
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Windows Server CPU Usage (instance {{ $labels.instance }})"
        description: "CPU Usage is more than 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: WindowsServerMemoryUsage
      expr: 100 * (wmi_os_physical_memory_free_bytes) / wmi_cs_physical_memory_bytes > 70
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Windows Server memory Usage (instance {{ $labels.instance }})"
        description: "Memory usage is more than 70%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"